networks:
  gitea:
    external: true

services:
  server:
    image: docker.io/gitea/gitea:1.22.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${GITEA_DATABASE_USER}
      - GITEA__database__PASSWD=${GITEA_DATABASE_PASSWORD}
      - GITEA__database__SSL_MODE=require
      - GITEA__database__SSL_ROOT_CERT=/data/certs/root_ca.crt
      - GITEA__database__SSL_CERT=/data/certs/gitea.crt
      - GITEA__database__SSL_KEY=/data/certs/gitea.key
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - ./certs/gitea/gitea.crt:/data/certs/gitea.crt:ro
      - ./certs/gitea/gitea.key:/data/certs/gitea.key:ro
      - ./certs/gitea/root_ca.crt:/data/certs/root_ca.crt:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
    ports:
      - "222:22"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./certs/postgres/postgres.crt:/var/lib/postgresql/server.crt:ro
      - ./certs/postgres/postgres.key:/var/lib/postgresql/server.key:ro
      - ./certs/postgres/root_ca.crt:/var/lib/postgresql/root.crt:ro
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c ssl_ca_file=/var/lib/postgresql/root.crt